name: libmoca
description: libmoca library for dart
repository: https://github.com/team-moca/moca-proto
issue_tracker: https://github.com/team-moca/moca-proto/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  async: ^2.2.0
  grpc: ^2.1.0